### ISSUE TITLE
Unavailable parts

### ISSUE THREAD

**Issue by BadAd84** [jago85/UltraPIF_Hardware#1]
Hi,

Looking at getting a batch of these made for our store. However, the STM32F070CBT6 and SI5351A-B-GTR are basically not available for a year+ due to shortages.

Is there any sort of alternative or redesign planned? I assume you are seeing this issue too (or maybe not, as not making many??)

**Comment by jago85** [comment]
Hi,

sorry for the delay. Due to a lack of time, I'm pretty inactive right now.

Unfortunatelly, I don't have any alternatives or redesign. There may be some compatible devices for the STM32, but I have no idea how to replace the clock generator. Having different parts would also make firmware updates much more complex. I wouldn't have the time for a re-design anyway. I didn't even manage to sort and upload all the software stuff here. (All N64 software and initialization tools are missing here.)

But I know Romi from ModInFrance managed to produce a batch and he can make a good reseller price. You might ask him if you like. [https://shop.modinfrance.fr/fr/nintendo-64/25-115-ultra-pif-nintendo-64.html](https://shop.modinfrance.fr/fr/nintendo-64/25-115-ultra-pif-nintendo-64.html)

**Comment by BadAd84** [comment]
That all makes sense, especially around firmware. I have an order in that's just waiting on stock.

Could you send me the extra tools/files required? I could always fork and add it and submit a pull request if it helps you with time etc. I have been maintaining the cdi and 3do rgb mod repos since the owners discontinued them

**Comment by jago85** [comment]
Sorry, I cannot send out the firmware at the moment. You should talk to Romi for further details.
